### ISSUE TITLE
azurekinect.exe cant find cubemos_skeleton_tracking.dll

### ISSUE THREAD

**Issue by pajama** [UnaNancyOwen/CubemosSample#2]
The sample builds fine. CMake is able to find my Cubemos installation, however when I run azurekinect.exe I get the error

> The code execution cannot proceed because cubemos_skeleton_tracking.dll was not found. Reinstalling the program may fix the problem

Thanks so much for the help!

**Comment by pajama** [comment]
Copying that dll to the folder that contains azurekinect.exe clears that error, but then it complains about the next dll, k4a.dll, then cubemos_engine.dll, etc.

These dlls are in the system path. Is there another way the app expects to find them? Should the build process be copying the dlls over and something is going wrong there? Or should I be doing this manually?

Thanks so much!

**Comment by UnaNancyOwen** [comment]
You need to set environment variable "Path" to the path of directory that contain these dll files, and restart OS to apply settings.
They are questions about Windows, or dependent libraries. Please ask questions in appropriate forum.

**Comment by pajama** [comment]
Hmm unfortunately these dlls are in the system path. The other cubemos and azure kinect samples build fine and copy the dlls successfully, so I thought maybe it was a cmake issue with this project in particular. I'll dig deeper.
